### ISSUE TITLE
About ccsmethphase output path 

### ISSUE THREAD

**Issue by Duyh814** [PengNi/ccsmethphase#1]
Hello from a new users 
It seems that the output path is not set, How should I set the output path for my file?  
And another question about  Will you consider directly performing DMR analysis on data from different groups within the program?

**Comment by PengNi** [comment]
Hi @Duyh814 , the output path can be setted by `--outdir`, the task name is setted by `--dsname`.

Thank you for the suggestion! I will consider DMR analysis between two different groups. But right now I don't have an exact time schedule for it. Once I complete, I will let you know ASAP.

**Comment by Duyh814** [comment]
Thanks for ur reply !
